# Generated by Django 6.0.3 on 2026-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='manual',
            name='offTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='manual',
            name='onTime',
            field=models.TimeField(),
        ),
    ]
