# Generated by Django 6.0.3 on 2026-03-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0002_manual_status_alter_manual_offtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theshold', models.IntegerField()),
                ('offDelay', models.IntegerField()),
                ('staus', models.BooleanField(default=True)),
            ],
        ),
    ]
