# Generated by Django 6.0.3 on 2026-03-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0003_motion'),
    ]

    operations = [
        migrations.CreateModel(
            name='sharedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.BooleanField(default=True)),
                ('fan', models.BooleanField(default=True)),
                ('autoMode', models.BooleanField(default=True)),
            ],
        ),
    ]
