# Generated by Django 6.0.3 on 2026-03-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0004_shareddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareddata',
            name='autoMode',
        ),
    ]
