# Generated by Django 6.0.3 on 2026-03-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0006_sensor_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motion',
            old_name='staus',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='motion',
            old_name='theshold',
            new_name='threshold',
        ),
    ]
