# Generated by Django 6.0.3 on 2026-03-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0007_rename_staus_motion_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='manual',
            new_name='ManualSchedule',
        ),
        migrations.RenameModel(
            old_name='sharedData',
            new_name='RelayControls',
        ),
        migrations.RenameModel(
            old_name='sensor_data',
            new_name='SensorData',
        ),
    ]
